# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            jae's memorylane
tagline:          'jae's memorylane'
description:      '@jaebyjae.com 2020'
url:              
baseurl:          /

author:
  name:           'jae'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
